package model;
// Generated 01/10/2019 21:48:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dose generated by hbm2java
 */
@Entity
@Table(name="dose"
    ,catalog="pep_hl7"
)
public class Dose  implements java.io.Serializable {


     private int idDose;
     private Integer num;
     private Set<VacinaAplicada> vacinaAplicadas = new HashSet<VacinaAplicada>(0);

    public Dose() {
    }

	
    public Dose(int idDose) {
        this.idDose = idDose;
    }
    public Dose(int idDose, Integer num, Set<VacinaAplicada> vacinaAplicadas) {
       this.idDose = idDose;
       this.num = num;
       this.vacinaAplicadas = vacinaAplicadas;
    }
   
     @Id 

    
    @Column(name="idDOSE", unique=true, nullable=false)
    public int getIdDose() {
        return this.idDose;
    }
    
    public void setIdDose(int idDose) {
        this.idDose = idDose;
    }

    
    @Column(name="NUM")
    public Integer getNum() {
        return this.num;
    }
    
    public void setNum(Integer num) {
        this.num = num;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dose")
    public Set<VacinaAplicada> getVacinaAplicadas() {
        return this.vacinaAplicadas;
    }
    
    public void setVacinaAplicadas(Set<VacinaAplicada> vacinaAplicadas) {
        this.vacinaAplicadas = vacinaAplicadas;
    }




}


