package model;
// Generated 01/10/2019 21:48:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FuncionarioId generated by hbm2java
 */
@Embeddable
public class FuncionarioId  implements java.io.Serializable {


     private int idfuncionario;
     private int vacinaAplicadaIdVacinaAplicada;
     private int vacinaAplicadaDoseIdDose;

    public FuncionarioId() {
    }

    public FuncionarioId(int idfuncionario, int vacinaAplicadaIdVacinaAplicada, int vacinaAplicadaDoseIdDose) {
       this.idfuncionario = idfuncionario;
       this.vacinaAplicadaIdVacinaAplicada = vacinaAplicadaIdVacinaAplicada;
       this.vacinaAplicadaDoseIdDose = vacinaAplicadaDoseIdDose;
    }
   


    @Column(name="idfuncionario", nullable=false)
    public int getIdfuncionario() {
        return this.idfuncionario;
    }
    
    public void setIdfuncionario(int idfuncionario) {
        this.idfuncionario = idfuncionario;
    }


    @Column(name="VACINA_APLICADA_idVACINA_APLICADA", nullable=false)
    public int getVacinaAplicadaIdVacinaAplicada() {
        return this.vacinaAplicadaIdVacinaAplicada;
    }
    
    public void setVacinaAplicadaIdVacinaAplicada(int vacinaAplicadaIdVacinaAplicada) {
        this.vacinaAplicadaIdVacinaAplicada = vacinaAplicadaIdVacinaAplicada;
    }


    @Column(name="VACINA_APLICADA_DOSE_idDOSE", nullable=false)
    public int getVacinaAplicadaDoseIdDose() {
        return this.vacinaAplicadaDoseIdDose;
    }
    
    public void setVacinaAplicadaDoseIdDose(int vacinaAplicadaDoseIdDose) {
        this.vacinaAplicadaDoseIdDose = vacinaAplicadaDoseIdDose;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FuncionarioId) ) return false;
		 FuncionarioId castOther = ( FuncionarioId ) other; 
         
		 return (this.getIdfuncionario()==castOther.getIdfuncionario())
 && (this.getVacinaAplicadaIdVacinaAplicada()==castOther.getVacinaAplicadaIdVacinaAplicada())
 && (this.getVacinaAplicadaDoseIdDose()==castOther.getVacinaAplicadaDoseIdDose());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdfuncionario();
         result = 37 * result + this.getVacinaAplicadaIdVacinaAplicada();
         result = 37 * result + this.getVacinaAplicadaDoseIdDose();
         return result;
   }   


}


