package model;
// Generated 01/10/2019 21:48:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistoricoAtendimento generated by hbm2java
 */
@Entity
@Table(name="historico_atendimento"
    ,catalog="pep_hl7"
)
public class HistoricoAtendimento  implements java.io.Serializable {


     private int idhistoricoAtendimento;
     private Integer registro;
     private Date data;
     private Set<Paciente> pacientes = new HashSet<Paciente>(0);

    public HistoricoAtendimento() {
    }

	
    public HistoricoAtendimento(int idhistoricoAtendimento) {
        this.idhistoricoAtendimento = idhistoricoAtendimento;
    }
    public HistoricoAtendimento(int idhistoricoAtendimento, Integer registro, Date data, Set<Paciente> pacientes) {
       this.idhistoricoAtendimento = idhistoricoAtendimento;
       this.registro = registro;
       this.data = data;
       this.pacientes = pacientes;
    }
   
     @Id 

    
    @Column(name="idhistorico_atendimento", unique=true, nullable=false)
    public int getIdhistoricoAtendimento() {
        return this.idhistoricoAtendimento;
    }
    
    public void setIdhistoricoAtendimento(int idhistoricoAtendimento) {
        this.idhistoricoAtendimento = idhistoricoAtendimento;
    }

    
    @Column(name="registro")
    public Integer getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Integer registro) {
        this.registro = registro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="historicoAtendimento")
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }




}


