package model;
// Generated 01/10/2019 21:48:18 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,catalog="pep_hl7"
)
public class Paciente  implements java.io.Serializable {


     private PacienteId id;
     private HistoricoAtendimento historicoAtendimento;
     private VacinaAplicada vacinaAplicada;
     private String nome;
     private String sexo;
     private Date dataNascimento;
     private String cpf;
     private String rg;
     private String telefone;
     private String celular;
     private String email;
     private String pais;
     private String uf;
     private String cidade;
     private String logradouro;
     private String bairro;
     private String cep;
     private String cartaoSus;
     private String estadoCivil;
     private String mae;

    public Paciente() {
    }

	
    public Paciente(PacienteId id, HistoricoAtendimento historicoAtendimento, VacinaAplicada vacinaAplicada) {
        this.id = id;
        this.historicoAtendimento = historicoAtendimento;
        this.vacinaAplicada = vacinaAplicada;
    }
    public Paciente(PacienteId id, HistoricoAtendimento historicoAtendimento, VacinaAplicada vacinaAplicada, String nome, String sexo, Date dataNascimento, String cpf, String rg, String telefone, String celular, String email, String pais, String uf, String cidade, String logradouro, String bairro, String cep, String cartaoSus, String estadoCivil, String mae) {
       this.id = id;
       this.historicoAtendimento = historicoAtendimento;
       this.vacinaAplicada = vacinaAplicada;
       this.nome = nome;
       this.sexo = sexo;
       this.dataNascimento = dataNascimento;
       this.cpf = cpf;
       this.rg = rg;
       this.telefone = telefone;
       this.celular = celular;
       this.email = email;
       this.pais = pais;
       this.uf = uf;
       this.cidade = cidade;
       this.logradouro = logradouro;
       this.bairro = bairro;
       this.cep = cep;
       this.cartaoSus = cartaoSus;
       this.estadoCivil = estadoCivil;
       this.mae = mae;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPaciente", column=@Column(name="idPACIENTE", nullable=false) ), 
        @AttributeOverride(name="vacinaAplicadaIdVacinaAplicada", column=@Column(name="VACINA_APLICADA_idVACINA_APLICADA", nullable=false) ), 
        @AttributeOverride(name="vacinaAplicadaDoseIdDose", column=@Column(name="VACINA_APLICADA_DOSE_idDOSE", nullable=false) ), 
        @AttributeOverride(name="vacinaIdVacina", column=@Column(name="VACINA_idVACINA", nullable=false) ), 
        @AttributeOverride(name="vacinaEstoqueIdEstoque", column=@Column(name="VACINA_ESTOQUE_idESTOQUE", nullable=false) ), 
        @AttributeOverride(name="historicoAtendimentoIdhistoricoAtendimento", column=@Column(name="historico_atendimento_idhistorico_atendimento", nullable=false) ) } )
    public PacienteId getId() {
        return this.id;
    }
    
    public void setId(PacienteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="historico_atendimento_idhistorico_atendimento", nullable=false, insertable=false, updatable=false)
    public HistoricoAtendimento getHistoricoAtendimento() {
        return this.historicoAtendimento;
    }
    
    public void setHistoricoAtendimento(HistoricoAtendimento historicoAtendimento) {
        this.historicoAtendimento = historicoAtendimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="VACINA_APLICADA_idVACINA_APLICADA", referencedColumnName="idVACINA_APLICADA", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="VACINA_APLICADA_DOSE_idDOSE", referencedColumnName="DOSE_idDOSE", nullable=false, insertable=false, updatable=false) } )
    public VacinaAplicada getVacinaAplicada() {
        return this.vacinaAplicada;
    }
    
    public void setVacinaAplicada(VacinaAplicada vacinaAplicada) {
        this.vacinaAplicada = vacinaAplicada;
    }

    
    @Column(name="NOME", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="SEXO", length=2)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATA_NASCIMENTO", length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="CPF", length=45)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="RG", length=45)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="TELEFONE", length=45)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="CELULAR", length=45)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="EMAIL", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="PAIS", length=45)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="UF", length=45)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    
    @Column(name="CIDADE", length=45)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="LOGRADOURO", length=45)
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    
    @Column(name="BAIRRO", length=45)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="CEP", length=45)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="CARTAO_SUS", length=45)
    public String getCartaoSus() {
        return this.cartaoSus;
    }
    
    public void setCartaoSus(String cartaoSus) {
        this.cartaoSus = cartaoSus;
    }

    
    @Column(name="ESTADO_CIVIL", length=45)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    
    @Column(name="MAE", length=45)
    public String getMae() {
        return this.mae;
    }
    
    public void setMae(String mae) {
        this.mae = mae;
    }




}


