package model;
// Generated 01/10/2019 21:48:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VacinaAplicadaId generated by hbm2java
 */
@Embeddable
public class VacinaAplicadaId  implements java.io.Serializable {


     private int idVacinaAplicada;
     private int doseIdDose;

    public VacinaAplicadaId() {
    }

    public VacinaAplicadaId(int idVacinaAplicada, int doseIdDose) {
       this.idVacinaAplicada = idVacinaAplicada;
       this.doseIdDose = doseIdDose;
    }
   


    @Column(name="idVACINA_APLICADA", nullable=false)
    public int getIdVacinaAplicada() {
        return this.idVacinaAplicada;
    }
    
    public void setIdVacinaAplicada(int idVacinaAplicada) {
        this.idVacinaAplicada = idVacinaAplicada;
    }


    @Column(name="DOSE_idDOSE", nullable=false)
    public int getDoseIdDose() {
        return this.doseIdDose;
    }
    
    public void setDoseIdDose(int doseIdDose) {
        this.doseIdDose = doseIdDose;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VacinaAplicadaId) ) return false;
		 VacinaAplicadaId castOther = ( VacinaAplicadaId ) other; 
         
		 return (this.getIdVacinaAplicada()==castOther.getIdVacinaAplicada())
 && (this.getDoseIdDose()==castOther.getDoseIdDose());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVacinaAplicada();
         result = 37 * result + this.getDoseIdDose();
         return result;
   }   


}


